import React,{useEffect,useState}from'react';
import{Alert,Linking,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from'react-native';
import{startBackgroundTracking,stopBackgroundTracking,isBackgroundTrackingActive,setActiveDelivery}from'./src/backgroundLocation';

const API=process.env.EXPO_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const C={bg:'#020611',panel:'#071226',line:'#17345D',gold:'#F5C443',blue:'#16B7FF',text:'#F5F8FF',muted:'#8FA4C7',green:'#67E5A5',red:'#FF6B6B'};
async function req(path:string,opt:any={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok){const e=await r.json().catch(()=>({detail:'Error'}));throw new Error(e.detail||'Error')}return r.json()}
const labels:any={ASSIGNED:'ASIGNADO',PICKED_UP:'RETIRADO',ON_THE_WAY:'EN CAMINO',DELIVERED:'ENTREGADO'};

export default function App(){const[me,setMe]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[tracking,setTracking]=useState(false),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 async function load(){try{setErr('');const[m,d,t]=await Promise.all([req('/courier/me'),req('/courier/deliveries'),isBackgroundTrackingActive()]);setMe(m);setRows(d);setTracking(t)}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load();const t=setInterval(load,12000);return()=>clearInterval(t)},[]);
 const active=rows.find(x=>x.delivery&&['ASSIGNED','PICKED_UP','ON_THE_WAY'].includes(x.status));
 async function availability(){try{const r=await req('/courier/availability',{method:'PATCH',body:JSON.stringify({available:!me.available})});setMe({...me,available:r.available})}catch(e:any){Alert.alert('Error',e.message)}}
 async function start(){if(!active?.delivery?.id)return Alert.alert('Sin entrega activa','Necesitas una entrega asignada para compartir ubicación.');try{setBusy(true);await startBackgroundTracking(active.delivery.id);setTracking(true)}catch(e:any){Alert.alert('GPS',e.message)}finally{setBusy(false)}}
 async function stop(){try{setBusy(true);await stopBackgroundTracking();setTracking(false)}finally{setBusy(false)}}
 async function advance(o:any){if(!o.delivery)return;const next=o.status==='ASSIGNED'?'PICKED_UP':o.status==='PICKED_UP'?'ON_THE_WAY':o.status==='ON_THE_WAY'?'DELIVERED':null;if(!next)return;try{setBusy(true);if(!tracking&&next!=='DELIVERED')await startBackgroundTracking(o.delivery.id);const r=await req(`/courier/deliveries/${o.delivery.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});if(next==='DELIVERED'){await stopBackgroundTracking();setTracking(false)}else await setActiveDelivery(o.delivery.id);await load();Alert.alert('Actualizado',`Pedido ${labels[r.status]||r.status}`)}catch(e:any){Alert.alert('Error',e.message)}finally{setBusy(false)}}
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.pad}><Text style={s.eyebrow}>LAYA MARKET CADETES</Text><Text style={s.h1}>{me?.name||'Panel del cadete'}</Text><Text style={s.muted}>{me?.city||''}</Text>{err?<View style={s.error}><Text style={s.errorText}>{err}</Text></View>:null}<View style={s.toolbar}><Pressable style={[s.button,me?.available&&s.buttonGreen]} onPress={availability}><Text style={s.buttonText}>{me?.available?'Disponible':'No disponible'}</Text></Pressable><Pressable disabled={busy} style={[s.button,tracking&&s.buttonBlue]} onPress={tracking?stop:start}><Text style={s.buttonText}>{tracking?'Detener GPS':'Iniciar GPS'}</Text></Pressable></View><View style={s.status}><Text style={s.statusTitle}>{tracking?'● GPS activo en segundo plano':'○ GPS detenido'}</Text><Text style={s.muted}>{tracking?'La ubicación continúa compartiéndose con la pantalla bloqueada mientras el sistema permita el servicio.':'Actívalo al comenzar una entrega.'}</Text></View>{!rows.length?<View style={s.empty}><Text style={s.muted}>No tienes entregas asignadas.</Text></View>:rows.map(o=><View style={s.card} key={o.id}><View style={s.row}><View><Text style={s.eyebrow}>PEDIDO #{o.id.slice(0,8)}</Text><Text style={s.h2}>{labels[o.status]||o.status}</Text></View><Text style={s.total}>{o.currency} {Number(o.total).toLocaleString()}</Text></View><Text style={s.text}><Text style={s.bold}>Comercio: </Text>{o.business_name}</Text><Text style={s.text}><Text style={s.bold}>Cliente: </Text>{o.customer_name}</Text><Text style={s.text}>{o.customer_phone||'Sin teléfono'}</Text><Text style={s.text}><Text style={s.bold}>Entrega: </Text>{o.delivery_address}</Text><Pressable style={s.linkButton} onPress={()=>Linking.openURL(`https://www.google.com/maps?q=${o.delivery_latitude},${o.delivery_longitude}`)}><Text style={s.link}>Abrir navegación</Text></Pressable>{['ASSIGNED','PICKED_UP','ON_THE_WAY'].includes(o.status)&&<Pressable disabled={busy} style={s.primary} onPress={()=>advance(o)}><Text style={s.primaryText}>{o.status==='ASSIGNED'?'Confirmar retiro':o.status==='PICKED_UP'?'Salir a entrega':'Confirmar entrega'}</Text></Pressable>}</View>)}</ScrollView></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},pad:{padding:18,paddingBottom:60,gap:12},eyebrow:{color:C.blue,fontSize:12,fontWeight:'900',letterSpacing:1},h1:{color:C.text,fontSize:28,fontWeight:'900'},h2:{color:C.text,fontSize:20,fontWeight:'900'},muted:{color:C.muted},toolbar:{flexDirection:'row',gap:10},button:{flex:1,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:13,borderRadius:14,alignItems:'center'},buttonGreen:{borderColor:C.green},buttonBlue:{borderColor:C.blue},buttonText:{color:C.text,fontWeight:'900'},status:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,padding:14,borderRadius:15},statusTitle:{color:C.green,fontWeight:'900'},card:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,padding:15,borderRadius:16,gap:7},row:{flexDirection:'row',justifyContent:'space-between',gap:10},total:{color:C.gold,fontWeight:'900',fontSize:18},text:{color:C.text},bold:{fontWeight:'900'},primary:{backgroundColor:C.gold,padding:14,borderRadius:12,alignItems:'center',marginTop:6},primaryText:{color:'#071226',fontWeight:'900'},linkButton:{borderWidth:1,borderColor:C.line,padding:12,borderRadius:12,alignItems:'center'},link:{color:C.blue,fontWeight:'900'},error:{backgroundColor:'#35141B',padding:12,borderRadius:12},errorText:{color:'#FFB3BF',fontWeight:'800'},empty:{padding:30,alignItems:'center'}});
