import React,{useEffect,useState}from'react';
import{ActivityIndicator,Linking,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import LocationMap from'./LocationMap';

const API=process.env.EXPO_PUBLIC_API_URL||'http://localhost:8000/api/v1';
const C={bg:'#020611',panel:'#071226',panel2:'#0B1933',line:'#17345D',blue:'#16B7FF',gold:'#F5C443',text:'#F5F8FF',muted:'#8FA4C7',green:'#67E5A5',red:'#FF6B6B'};
async function api(path:string,opt:any={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok){const e=await r.json().catch(()=>({detail:'Error'}));throw new Error(e.detail||'Error')}return r.json()}
const money=(n:number,c:string)=>`${c} ${Number(n||0).toLocaleString()}`;
const labels:any={NEW:'RECIBIDO',ACCEPTED:'ACEPTADO',PREPARING:'PREPARANDO',READY:'LISTO',COURIER_REQUESTED:'BUSCANDO CADETE',ASSIGNED:'CADETE ASIGNADO',PICKED_UP:'RETIRADO',ON_THE_WAY:'EN CAMINO',DELIVERED:'ENTREGADO',CANCELLED:'CANCELADO'};

export default function CustomerOrders({rows,reload}:any){const[tab,setTab]=useState<'orders'|'notifications'>('orders'),[notes,setNotes]=useState<any[]>([]),[trackingId,setTrackingId]=useState<string|null>(null),[tracking,setTracking]=useState<any>(null),[loadingTrack,setLoadingTrack]=useState(false);
 async function loadNotes(){setNotes(await api('/notifications/my').catch(()=>[]))}
 async function refreshAll(){await Promise.all([reload?.(),loadNotes()])}
 useEffect(()=>{loadNotes();const t=setInterval(refreshAll,10000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!trackingId)return;let alive=true;async function poll(){try{const x=await api(`/tracking/orders/${trackingId}`);if(alive)setTracking(x)}catch{}finally{if(alive)setLoadingTrack(false)}}setLoadingTrack(true);poll();const t=setInterval(poll,5000);return()=>{alive=false;clearInterval(t)}},[trackingId]);
 async function openWhatsapp(orderId:string){const w=await api(`/whatsapp/contact?order_id=${orderId}`);await Linking.openURL(w.url)}
 async function markRead(n:any){if(!n.read){await api(`/notifications/${n.id}/read`,{method:'PATCH'});await loadNotes()}if(n.order_id)setTrackingId(n.order_id)}
 if(trackingId)return <Tracking orderId={trackingId} data={tracking} loading={loadingTrack} close={()=>{setTrackingId(null);setTracking(null)}} whatsapp={()=>openWhatsapp(trackingId)}/>;
 const unread=notes.filter(n=>!n.read).length;
 return <ScrollView style={s.bg} contentContainerStyle={s.pad}><View style={s.tabs}><Pressable style={[s.tab,tab==='orders'&&s.tabActive]} onPress={()=>setTab('orders')}><Text style={s.tabText}>Pedidos</Text></Pressable><Pressable style={[s.tab,tab==='notifications'&&s.tabActive]} onPress={()=>setTab('notifications')}><Text style={s.tabText}>Notificaciones {unread?`(${unread})`:''}</Text></Pressable></View>{tab==='orders'?<><Text style={s.h1}>Mis pedidos</Text>{!rows.length?<Empty text="Todavía no tienes pedidos."/>:rows.map((o:any)=><View key={o.id} style={s.card}><View style={s.row}><Text style={s.title}>#{o.id.slice(0,8)}</Text><Text style={s.status}>{labels[o.status]||o.status}</Text></View><Text style={s.muted}>{o.delivery_method} · {o.distance_km??0} km</Text><Text style={s.muted}>{o.delivery_address||'Retiro en comercio'}</Text>{o.items?.map((i:any)=><Text key={i.id||i.product_id+(i.presentation_id||'')} style={s.small}>{i.quantity}× {i.name}{i.presentation_label?` · ${i.presentation_label}`:''}</Text>)}<Text style={s.total}>{money(o.total,o.currency)}</Text><Text style={s.small}>Pago: {o.payment_status}</Text><View style={s.actions}>{o.delivery_method==='COURIER'&&<Pressable style={s.primary} onPress={()=>setTrackingId(o.id)}><Text style={s.primaryText}>{['ASSIGNED','PICKED_UP','ON_THE_WAY'].includes(o.status)?'Ver cadete en vivo':'Ver estado de entrega'}</Text></Pressable>}<Pressable style={s.secondary} onPress={()=>openWhatsapp(o.id)}><Text style={s.secondaryText}>WhatsApp</Text></Pressable></View></View>)}</>:<><View style={s.row}><Text style={s.h1}>Notificaciones</Text><Pressable onPress={loadNotes}><Text style={s.link}>Actualizar</Text></Pressable></View>{!notes.length?<Empty text="No tienes notificaciones."/>:notes.map(n=><Pressable key={n.id} style={[s.card,!n.read&&{borderColor:C.gold}]} onPress={()=>markRead(n)}><View style={s.row}><Text style={s.title}>{n.title}</Text><Text style={s.small}>{n.read?'Leída':'Nueva'}</Text></View><Text style={s.muted}>{n.body}</Text><Text style={s.small}>{new Date(n.created_at).toLocaleString()}</Text></Pressable>)}</>}</ScrollView>}

function Tracking({orderId,data,loading,close,whatsapp}:any){const loc=data?.location,dest=data?.destination;const centerLat=loc?.latitude??dest?.latitude??-32.8895,centerLng=loc?.longitude??dest?.longitude??-68.8458;const markers:any[]=[];if(loc)markers.push({id:'courier',latitude:loc.latitude,longitude:loc.longitude,name:data?.courier?.name||'Cadete LAYA'});if(dest?.latitude&&dest?.longitude)markers.push({id:'destination',latitude:dest.latitude,longitude:dest.longitude,name:'Tu dirección'});return <ScrollView style={s.bg} contentContainerStyle={s.pad}><Pressable onPress={close}><Text style={s.link}>← Mis pedidos</Text></Pressable><Text style={s.h1}>Seguimiento #{orderId.slice(0,8)}</Text><Text style={s.status}>{labels[data?.status]||data?.status||'Consultando…'}</Text>{loading&&!data?<ActivityIndicator color={C.gold}/>:<><LocationMap latitude={centerLat} longitude={centerLng} markers={markers}/><View style={s.card}>{data?.courier?<><Text style={s.title}>{data.courier.name}</Text><Text style={s.muted}>{data.tracking_active?'Ubicación en tiempo real activa':'Seguimiento sin movimiento activo'}</Text></>:<Text style={s.muted}>Todavía no hay cadete asignado.</Text>}{loc?<><Text style={data?.stale?s.warn:s.ok}>{data?.stale?'Ubicación desactualizada':'Ubicación actualizada'}</Text><Text style={s.small}>Última señal: {new Date(loc.updated_at).toLocaleTimeString()} · precisión {Math.round(loc.accuracy||0)} m</Text></>:<Text style={s.small}>Esperando la primera señal GPS del cadete.</Text>}<Text style={s.small}>La posición se actualiza automáticamente cada 5 segundos en esta pantalla.</Text></View></>}<Pressable style={s.secondary} onPress={whatsapp}><Text style={s.secondaryText}>Contactar a LAYA por WhatsApp</Text></Pressable></ScrollView>}
function Empty({text}:any){return <View style={s.empty}><Text style={{fontSize:34}}>◈</Text><Text style={s.muted}>{text}</Text></View>}
const s=StyleSheet.create({bg:{flex:1,backgroundColor:C.bg},pad:{padding:16,paddingBottom:110,gap:10},tabs:{flexDirection:'row',gap:8},tab:{flex:1,borderWidth:1,borderColor:C.line,padding:11,borderRadius:12,alignItems:'center'},tabActive:{borderColor:C.gold,backgroundColor:C.panel2},tabText:{color:C.text,fontWeight:'900'},h1:{color:C.text,fontSize:27,fontWeight:'900'},card:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:14,padding:13,gap:6},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},title:{color:C.text,fontWeight:'900',fontSize:15},muted:{color:C.muted},small:{color:C.muted,fontSize:12},status:{color:C.green,fontWeight:'900'},total:{color:C.gold,fontSize:23,fontWeight:'900'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},primary:{backgroundColor:C.gold,padding:11,borderRadius:11},primaryText:{color:'#071226',fontWeight:'900'},secondary:{borderWidth:1,borderColor:C.line,padding:11,borderRadius:11},secondaryText:{color:C.text,fontWeight:'900'},link:{color:C.blue,fontWeight:'900'},ok:{color:C.green,fontWeight:'900',marginTop:5},warn:{color:C.gold,fontWeight:'900',marginTop:5},empty:{alignItems:'center',justifyContent:'center',padding:32,gap:8}});
